quotes = [{'author':'Nelson Mandela', 'body':'The greatest glory in living lies not in never falling, but in rising every time we fall.', 'emoji': '🌍✊❤️', 'id': 1},
    {'author':'Eleanor Roosevelt', 'body':'The future belongs to those who believe in the beauty of their dreams.', 'emoji': '🌸🎓📚', 'id': 2},
    {'author':'Steve Jobs', 'body':'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.', 'emoji': '📱🍏🚀', 'id': 3},
    {'author':'Oprah Winfrey', 'body':'The biggest adventure you can take is to live the life of your dreams.', 'emoji': '📺💬👑', 'id': 4},
    {'author':'Mahatma Gandhi', 'body':'Strength does not come from physical capacity. It comes from an indomitable will.', 'emoji': '🇮🇳🌿✋', 'id': 5},
    {'author':'Martin Luther King Jr.', 'body':'If you can’t fly then run, if you can’t run then walk, if you can’t walk then crawl, but whatever you do you have to keep moving forward.', 'emoji': '🌍✊🕊️', 'id': 6},
    {'author':'Rosa Parks', 'body':'You must never be fearful about what you are doing when it is right.', 'emoji': '🚌✊🌟', 'id': 7},
    {'author':'Walt Disney', 'body':'All our dreams can come true, if we have the courage to pursue them.', 'emoji': '🎢🎬✨', 'id': 8},
    {'author':'C.S. Lewis', 'body':'Hardships often prepare ordinary people for an extraordinary destiny.', 'emoji': '🦁📜✍️', 'id': 9},
    {'author':'Helen Keller', 'body':'Keep your face to the sunshine and you cannot see a shadow.', 'emoji': '🌞🌻📚', 'id': 10},
    {'author':'Maya Angelou', 'body':'You will face many defeats in life, but never let yourself be defeated.', 'emoji': '📘🕊️👒', 'id': 11},
    {'author':'Albert Einstein', 'body':'Life is like riding a bicycle. To keep your balance, you must keep moving.', 'emoji': '🔬🚴🌀', 'id': 12},
    {'author':'Mother Teresa', 'body':'Spread love everywhere you go. Let no one ever come to you without leaving happier.', 'emoji': '🌼🙏💛', 'id': 13},
    {'author':'Arnold Schwarzenegger', 'body':'Strength does not come from winning. Your struggles develop your strengths.', 'emoji': '💪🎬🏋️', 'id': 14},
    {'author':'Amelia Earhart', 'body':'The most difficult thing is the decision to act, the rest is merely tenacity.', 'emoji': '✈️👩‍✈️🌅', 'id': 15},
    {'author':'J.K. Rowling', 'body':'It does not do to dwell on dreams and forget to live.', 'emoji': '🧙‍♂️📚✨', 'id': 16},
    {'author':'Fred Rogers', 'body':'Often when you think you’re at the end of something, you’re at the beginning of something else.', 'emoji': '🧥🎞️👶', 'id': 17},
    {'author':'Franklin D. Roosevelt', 'body':'When you reach the end of your rope, tie a knot in it and hang on.', 'emoji': '🎖️🇺🇸💪', 'id': 18},
    {'author':'Serena Williams', 'body':'I really think a champion is defined not by their wins but by how they can recover when they fall.', 'emoji': '🎾🏆💪', 'id': 19},
    {'author':'Vincent Van Gogh', 'body':'Great things are done by a series of small things brought together.', 'emoji': '🎨🌻🖼️', 'id': 20},
    {'author':'Anne Frank', 'body':'In spite of everything, I still believe that people are really good at heart.', 'emoji': '📖🌈🌟', 'id': 21},
    {'author':'Ayn Rand', 'body':'The question isn’t who is going to let me; it’s who is going to stop me.', 'emoji': '📚🏛️🖋️', 'id': 22},
    {'author':'Dalai Lama', 'body':'The purpose of our lives is to be happy.', 'emoji': '🙏🇹🇭🌸', 'id': 23},
    {'author':'Henry Ford', 'body':'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.', 'emoji': '🚗🏭🛫', 'id': 24},
    {'author':'Malala Yousafzai', 'body':'One child, one teacher, one book, one pen can change the world.', 'emoji': '🎓✏️📚', 'id': 25},
    {'author':'Harriet Tubman', 'body':'Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.', 'emoji': '🚇✊🌠', 'id': 26},
    {'author':'Thomas Edison', 'body':'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.', 'emoji': '💡🔬⚡', 'id': 27},
    {'author':'Ruth Bader Ginsburg', 'body':'Fight for the things that you care about, but do it in a way that will lead others to join you.', 'emoji': '⚖️👩‍⚖️🌈', 'id': 28},
    {'author':'Vin Scully', 'body':'Good is not good when better is expected.', 'emoji': '📢⚾🏟️', 'id': 29},
    {'author':'Simone de Beauvoir', 'body':'Change your life today. Don’t gamble on the future, act now, without delay.', 'emoji': '✍️📚🌹', 'id': 30},
    {'author':'Shakespeare', 'body':'It is not in the stars to hold our destiny but in ourselves.', 'emoji': '🎭✒️🌌', 'id': 31},
    {'author':'Muhammad Ali', 'body':'Don’t count the days; make the days count.', 'emoji': '🥊✊🏆', 'id': 32},
    {'author':'Winston Churchill', 'body':'Success is not final, failure is not fatal: It is the courage to continue that counts.', 'emoji': '🥃🇬🇧🚬', 'id': 33},
    {'author':'Jane Goodall', 'body':'What you do makes a difference, and you have to decide what kind of difference you want to make.', 'emoji': '🐒🌍🌿', 'id': 34},
    {'author':'Leonardo da Vinci', 'body':'I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.', 'emoji': '🎨🖼️🌀', 'id': 35},
    {'author':'Marie Curie', 'body':'Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.', 'emoji': '🔬🧪💡', 'id': 36},
    {'author':'Babe Ruth', 'body':'You just can’t beat the person who never gives up.', 'emoji': '⚾🏅🏟️', 'id': 37},
    {'author':'Audrey Hepburn', 'body':'Nothing is impossible, the word itself says ‘I’m possible’!', 'emoji': '🎬🎩🌸', 'id': 38},
    {'author':'Benjamin Franklin', 'body':'Do not fear mistakes. You will know failure. Continue to reach out.', 'emoji': '💡📜🔔', 'id': 39},
    {'author':'Lance Armstrong', 'body':'Pain is temporary. Quitting lasts forever.', 'emoji': '🚴‍♂️🏆🌟', 'id': 40},
    {'author':'Zig Ziglar', 'body':'What you get by achieving your goals is not as important as what you become by achieving your goals.', 'emoji': '📘🗣🏆', 'id': 41},
    {'author':'Confucius', 'body':'It does not matter how slowly you go as long as you do not stop.', 'emoji': '📜🌀✌️', 'id': 42},
    {'author':'Florence Nightingale', 'body':'I attribute my success to this: I never gave or took any excuse.', 'emoji': '💊🩺🌹', 'id': 43},
    {'author':'Henry David Thoreau', 'body':'Go confidently in the direction of your dreams. Live the life you have imagined.', 'emoji': '✍️🌲🌌', 'id': 44},
    {'author':'Isaac Newton', 'body':'If I have seen further it is by standing on the shoulders of Giants.', 'emoji': '🍎💡🔬', 'id': 45},
    {'author':'Margaret Thatcher', 'body':'You may have to fight a battle more than once to win it.', 'emoji': '👜🇬🇧⚔️', 'id': 46},
    {'author':'Michael Jordan', 'body':'I’ve failed over and over and over again in my life and that is why I succeed.', 'emoji': '🏀🏆💪', 'id': 47},
    {'author':'Mahatma Gandhi', 'body':'Live as if you were to die tomorrow. Learn as if you were to live forever.', 'emoji': '🙏🇮🇳🌿', 'id': 48},
    {'author':'Susan B. Anthony', 'body':'Failure is impossible.', 'emoji': '✊📜🇺🇸', 'id': 49},
    {'author':'Walt Whitman', 'body':'Keep your face always toward the sunshine—and shadows will fall behind you.', 'emoji': '📖🌞🌊', 'id': 50},
    {'author':'Harper Lee', 'body':'Real courage is when you know you’re licked before you begin, but you begin anyway and see it through no matter what.', 'emoji': '🍃🖋📖', 'id': 51},
    {'author':'Eleanor Roosevelt', 'body':'You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face. You must do the thing you think you cannot do.', 'emoji': '📚🌹🗽', 'id': 52},
    {'author':'Isaac Asimov', 'body':'The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.', 'emoji': '📚🔬🤖', 'id': 53},
    {'author':'Nelson Mandela', 'body':'It always seems impossible until it’s done.', 'emoji': '🗝️🌍🕊️', 'id': 54},
    {'author':'Oprah Winfrey', 'body':'Turn your wounds into wisdom.', 'emoji': '🎤📚🌟', 'id': 55},
    {'author':'Alfred Lord Tennyson', 'body':'Hope Smiles from the threshold of the year to come, Whispering ‘it will be happier’…', 'emoji': '📝🌸🌅', 'id': 56},
    {'author':'J.K. Rowling', 'body':'The world is full of wonderful things you haven’t seen yet. Don’t ever give up on the chance of seeing them.', 'emoji': '🧙📖✨', 'id': 57},
    {'author':'Helen Keller', 'body':'The only thing worse than being blind is having sight but no vision.', 'emoji': '🔖🕊🗝️', 'id': 58},
    {'author':'Confucius', 'body':'The man who moves a mountain begins by carrying away small stones.', 'emoji': '🌀✌️⛰', 'id': 59},
    {'author':'Sylvester Stallone', 'body':'Every champion was once a contender that refused to give up.', 'emoji': '🥊🎬🏆', 'id': 60},
    {'author':'Simone Biles', 'body':'I’d rather regret the risks that didn’t work out than the chances I didn’t take at all.', 'emoji': '🤸‍♀️🎖🇺🇸', 'id': 61},
    {'author':'Michael Phelps', 'body':'You can’t put a limit on anything. The more you dream, the farther you get.', 'emoji': '🏊‍♂️🥇🌟', 'id': 62},
    {'author':'Helen Keller', 'body':'Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.', 'emoji': '🕊🌻💬', 'id': 63},
    {'author':'Alfred Hitchcock', 'body':'There is nothing as good as a good laugh.', 'emoji': '🎥🔍🎬', 'id': 64},
    {'author':'Mark Twain', 'body':'The secret of getting ahead is getting started.', 'emoji': '📚🌍🖋', 'id': 65},
    {'author':'Eleanor Roosevelt', 'body':'With the new day comes new strength and new thoughts.', 'emoji': '📚🌸✨', 'id': 66},
    {'author':'Winston Churchill', 'body':'To improve is to change; to be perfect is to change often.', 'emoji': '🇬🇧✌️🎖', 'id': 67},
    {'author':'Pablo Picasso', 'body':'Action is the foundational key to all success.', 'emoji': '🎨🖌️🖼️', 'id': 68},
    {'author':'Martha Graham', 'body':'Great dancers are not great because of their technique, they are great because of their passion.', 'emoji': '💃🎭🌟', 'id': 69},
    {'author':'James Cameron', 'body':'If you set your goals ridiculously high and it’s a failure, you will fail above everyone else’s success.', 'emoji': '🎥🌌🚀', 'id': 70},
    {'author':'Frida Kahlo', 'body':'At the end of the day, we can endure much more than we think we can.', 'emoji': '🖼️🎨🌹', 'id': 71},
    {'author':'Sojourner Truth', 'body':'Truth is powerful and it prevails.', 'emoji': '✊📜🌍', 'id': 72},
    {'author':'Jeff Bezos', 'body':'If you cannot get a miracle, become one.', 'emoji': '🚀📦💻', 'id': 73},
    {'author':'Billie Jean King', 'body':'Champions keep playing until they get it right.', 'emoji': '🎾🏆🇺🇸', 'id': 74},
    {'author':'Dolly Parton', 'body':'The way I see it, if you want the rainbow, you gotta put up with the rain.', 'emoji': '🎤🌈🦋', 'id': 75}
]